

class TABLE_NAME:
    ESTATES = "estates"
    FLAT_MODELS = "flat_models"
    FLAT_TYPES = "flat_types"
    HAWKER_CENTRES = "hawker_centres"
    MRT_LINES = "mrt_lines"
    MRT_STATIONS_LINES = "mrt_stations_lines"
    MRT_STATIONS = "mrt_stations"
    MRT_STATIONS_EXITS = "mrt_stations_exits"
    PARKS = "parks"
    PUBLIC_HOSPITALS = "public_hospitals"
    RESALE_FLATS = "resale_flats"
    RESALE_FLATS_GEOLOCATION = "resale_flats_geolocation"
    SCHOOLS = "schools"
    SHOPPING_MALLS = "shopping_malls"
    

class ID:
    BLOCK = "block"
    HAWKER_CENTRE_NAME = "hawker_centre_name"
    HOSPITAL_NAME = "hospital_name"
    MRT_LINE_NAME = "mrt_line_name"
    MRT_STATION_NAME = "mrt_station_name"
    PARK_NAME = "park_name"
    RESALE_FLAT_ID = "resale_flat_id"
    SCHOOL_NAME = "school_name"
    SHOPPING_MALL_NAME = "shopping_mall_name"
    STREET_NAME = "street_name"

class KEY_NAME:
    ESTATE = "estate"
    EXIT_CODE = "exit_code"
    LATITUDE = "latitude"
    LONGITUDE = "longitude"
    FLAT_MODEL = "flat_model"
    FLAT_TYPE = "flat_type"
    NAME = "name"
    PHOTO_URL = "photo_url"
    REMAINING_LEASE = "remaining_lease"
    REMAINING_LEASE_MONTHS = "remaining_lease_months"
    REMAINING_LEASE_YEARS = "remaining_lease_years"
    SOLD_DATE = "sold_date"
    STOREY_RANGE = "storey_range"
    STOREY_RANGE_END = "storey_range_end"
    STOREY_RANGE_START = "storey_range_start"
    TOWN = "town"
